apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: jenkins-developer
spec:
  podSelector:
    matchLabels:
      jenkins/role: backend   # adapte selon le label exact de ton pod
  policyTypes:
    - Egress
  egress: []   # Pas de règle egress => bloque tout trafic sortant
