apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-internet
  namespace: jenkins-developer
spec:
  podSelector:
    matchLabels:
      jenkins/label: jenkins-backend-build
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8    # Autorise le trafic interne au cluster (DNS, services)
        - ipBlock:
            cidr: 127.0.0.0/8   # Loopback local
      ports:
        - protocol: UDP
          port: 53              # DNS
        - protocol: TCP
          port: 53
