apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-internet
  namespace: jenkins-developer
spec:
  podSelector:
    matchLabels:
      jenkins/role: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8       # réseau interne cluster
        - ipBlock:
            cidr: 127.0.0.0/8      # loopback local
      ports:
        - protocol: UDP
          port: 53                 # DNS
        - protocol: TCP
          port: 53
