pipeline {
  agent {
    kubernetes {
      label 'jenkins-frontend'
      defaultContainer 'helm'
      namespace 'jenkins-developer'
      serviceAccount 'jenkins-deployer'
    }
  }

  environment {
    KUBECONFIG_PATH = '/home/jenkins/.kube/config'
    CHART_PATH = './charts/frontend-chart'
    NAMESPACE = 'jenkins-developer'
  }

  stages {
    stage('Deploy Frontend') {
      steps {

          sh '''
           echo "DEBUG: deploy frontend"
           KUBECONFIG=${KUBECONFIG_PATH} helm upgrade --install todo-frontend ./charts/frontend-chart -f ./charts/frontend-chart/values.yaml --namespace jenkins-developer
          '''

      }
    }

    stage('Verify') {
             steps {
               echo " Déploiement Frontend réussi dans le namespace ${NAMESPACE}"
             }
           }
  }


}
