version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE:-todo-backend}:latest
    ports:
      - "3001:3000"
    volumes:
      - todo-app_todo-data:/app/src/data
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE:-todo-frontend}:latest
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3001
    restart: unless-stopped

volumes:
  todo-app_todo-data:
    driver: local
