version: '3.8'

services:
  frontend:
    image: todo-frontend:latest
    ports:
      - "8081:80"
    networks:
      - todo-network

  backend:
    image: todo-backend:latest
    ports:
      - "3001:3000"
    networks:
      - todo-network

networks:
  todo-network:
    external: true
