pipeline {
  agent { label 'frontend' }

    parameters {
    string(name: 'IMAGE_NAME', defaultValue: 'todo-frontend:latest')
        string(name: 'NETWORK_NAME', defaultValue: 'todo-network')
    }

    stages {
    stage('Checkout') {
      steps {
        dir('To_Do_List') {
          checkout scm
                }
            }
        }

        stage('Build & Test') {
      steps {
        dir('To_Do_List') {

                }
            }
        }

        stage('Build Docker Image') {
      steps {
        dir('To_Do_List') {
          sh "docker build -t ${params.IMAGE_NAME} ."
                }
            }
        }
    }

    post {
    success {
      echo "Frontend build terminé avec succès !"
        }
        failure {
      echo "Frontend build échoué."
        }
    }
}
