app:
  name: todo-frontend
  image:
    repository: inestmimi123/todo-frontend
    tag: latest
  port: 80
  targetPort: 80

# Service Account configuration
serviceAccount:
  create: false
  name: jenkins-deployer
  annotations: {}

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Deployment configuration
deployment:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Persistent Volume - RÉFÉRENCE À UN PVC EXISTANT
persistence:
  enabled: true
  # NOM DU PVC PRÉ-CRÉÉ (ne crée plus de PVC)
  existingClaim: "todo-frontend-cache-pvc"
  # Chemin de montage pour le cache nginx
  mountPath: "/var/cache/nginx"

# Ingress configuration (optional)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: todo-frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Node selector, tolerations and affinity
nodeSelector: {}
tolerations: []
affinity: {}