# charts/backend-chart/values.yaml

# Application settings
app:
  name: todo-backend
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: IfNotPresent
  
  port: 3000
  targetPort: 3000

# Service Account configuration
serviceAccount:
  create: false
  name: jenkins-deployer
  # Annotations to add to the service account
  annotations: {}

# Service configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Deployment configuration
deployment:
  replicaCount: 1
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Environment variables
env:
  NODE_ENV: production
  PORT: 3000

# Persistent Volume (if needed for data storage)
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# Ingress configuration (optional)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: todo-backend.local
      paths:
        - path: /api
          pathType: Prefix
  tls: []

# Node selector, tolerations and affinity
nodeSelector: {}
tolerations: []
affinity: {}