pipeline {
  agent {
    kubernetes {
      label 'jenkins-backend'
      defaultContainer 'helm'
      namespace 'default'
      serviceAccount 'jenkins-deployer'
    }
  }

  environment {
    KUBECONFIG_PATH = '/home/jenkins/.kube/config'
    CHART_PATH = './charts/backend-chart'
    NAMESPACE = 'jenkins-developer'
  }

  stages {
    stage('Deploy Backend') {
      steps {

          sh '''
            echo "DEBUG: deploy backend"
            KUBECONFIG=${KUBECONFIG_PATH} helm upgrade --install todo-backend ./charts/backend-chart -f ./charts/backend-chart/values.yaml
          '''

      }
    }

   stage('Verify') {
         steps {
           echo " Déploiement Backend réussi dans le namespace ${NAMESPACE}"
         }
       }
  }


}
