pipeline {
	agent { label 'backend' }

    parameters {
		string(name: 'IMAGE_NAME', defaultValue: 'todo-backend:latest')
        string(name: 'NETWORK_NAME', defaultValue: 'todo-network')
    }

    stages {
		stage('Checkout') {
			steps {
				dir('To_Do_List_Backend') {
					checkout scm
                }
            }
        }

        stage('Build & Test') {
			steps {
				dir('To_Do_List_Backend') {

                }
            }
        }

        stage('Build Docker Image') {
			steps {
				dir('To_Do_List_Backend') {
					sh "docker build -t ${params.IMAGE_NAME} ."
                }
            }
        }
    }

    post {
		success {
			echo "Backend build terminé avec succès !"
        }
        failure {
			echo "Backend build échoué."
        }
    }
}